<a href="https://colab.research.google.com/github/jashwanthd19/IDRA-Assignments/blob/main/Numpy_Practice_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

print("NumPy version:", np.__version__)

array_1d = np.array([10, 20, 30, 40, 50])

array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

array_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("1D Array:")
print(array_1d)

print("\n2D Array:")
print(array_2d)

print("\n3D Array:")
print(array_3d)

print("\n1D Array")
print("Dimensions:", array_1d.ndim)
print("Shape:", array_1d.shape)
print("Size:", array_1d.size)
print("Data Type:", array_1d.dtype)

print("\n2D Array")
print("Dimensions:", array_2d.ndim)
print("Shape:", array_2d.shape)
print("Size:", array_2d.size)
print("Data Type:", array_2d.dtype)

print("\n3D Array")
print("Dimensions:", array_3d.ndim)
print("Shape:", array_3d.shape)
print("Size:", array_3d.size)
print("Data Type:", array_3d.dtype)

print("\nIndexing")
print("First element:", array_1d[0])
print("Last element:", array_1d[-1])
print("2D element:", array_2d[0, 1])
print("3D element:", array_3d[1, 0, 1])

print("\nSlicing")
print("1D slice:", array_1d[1:4])
print("2D slice:")
print(array_2d[0:2, 1:3])
print("First column:", array_2d[:, 0])
print("Second row:", array_2d[1, :])

numbers = np.arange(1, 13)

print("\nOriginal Array:")
print(numbers)
print("Original Shape:", numbers.shape)

reshaped = numbers.reshape(3, 4)

print("\nReshaped Array:")
print(reshaped)
print("New Shape:", reshaped.shape)

zeros_array = np.zeros((2, 3))
ones_array = np.ones((2, 3))
range_array = np.arange(0, 10, 2)
linear_array = np.linspace(0, 1, 5)

print("\nZeros:")
print(zeros_array)

print("\nOnes:")
print(ones_array)

print("\nArange:")
print(range_array)

print("\nLinspace:")
print(linear_array)

a = np.array([10, 20, 30, 40])
b = np.array([2, 4, 5, 8])

print("\nMathematical Operations")
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Square:", a ** 2)
print("Square Root:", np.sqrt(a))

marks = np.array([45, 60, 72, 81, 90])

updated_marks = marks + 5
doubled_marks = marks * 2

print("\nVectorized Operations")
print("Original Marks:", marks)
print("After adding 5:", updated_marks)
print("After multiplying by 2:", doubled_marks)

marks = np.array([35, 48, 56, 67, 72, 85, 91])

mask = marks >= 60

print("\nBoolean Masking")
print("Marks:", marks)
print("Boolean Mask:", mask)
print("Marks >= 60:", marks[mask])

middle_marks = marks[(marks >= 50) & (marks <= 80)]

print("Marks between 50 and 80:", middle_marks)

sales = np.array([
    [100, 200, 300],
    [150, 250, 350]
])

tax = np.array([10, 20, 30])

total_sales = sales + tax

print("\nBroadcasting")
print("Sales:")
print(sales)

print("Tax:")
print(tax)

print("Sales after adding tax:")
print(total_sales)

data = np.array([10, 20, 30, 40, 50])

print("\nAggregate Functions")
print("Data:", data)
print("Sum:", np.sum(data))
print("Mean:", np.mean(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Median:", np.median(data))

data_2d = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("\n2D Aggregate Functions")
print(data_2d)
print("Sum:", np.sum(data_2d))
print("Mean:", np.mean(data_2d))
print("Minimum:", np.min(data_2d))
print("Maximum:", np.max(data_2d))
print("Median:", np.median(data_2d))
print("Column-wise Sum:", np.sum(data_2d, axis=0))
print("Row-wise Sum:", np.sum(data_2d, axis=1))

student_marks = np.array([78, 65, 89, 92, 55, 73, 88, 95, 61, 84])

average = np.mean(student_marks)
highest = np.max(student_marks)
lowest = np.min(student_marks)
median = np.median(student_marks)
passed = student_marks[student_marks >= 50]

print("\nNumerical Data Analysis")
print("Student Marks:", student_marks)
print("Average:", average)
print("Highest:", highest)
print("Lowest:", lowest)
print("Median:", median)
print("Passed Students:", passed)
print("Number of Students Passed:", passed.size)

NumPy version: 2.0.2
1D Array:
[10 20 30 40 50]

2D Array:
[[1 2 3]
 [4 5 6]]

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

1D Array
Dimensions: 1
Shape: (5,)
Size: 5
Data Type: int64

2D Array
Dimensions: 2
Shape: (2, 3)
Size: 6
Data Type: int64

3D Array
Dimensions: 3
Shape: (2, 2, 2)
Size: 8
Data Type: int64

Indexing
First element: 10
Last element: 50
2D element: 2
3D element: 6

Slicing
1D slice: [20 30 40]
2D slice:
[[2 3]
 [5 6]]
First column: [1 4]
Second row: [4 5 6]

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Original Shape: (12,)

Reshaped Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
New Shape: (3, 4)

Zeros:
[[0. 0. 0.]
 [0. 0. 0.]]

Ones:
[[1. 1. 1.]
 [1. 1. 1.]]

Arange:
[0 2 4 6 8]

Linspace:
[0.   0.25 0.5  0.75 1.  ]

Mathematical Operations
Addition: [12 24 35 48]
Subtraction: [ 8 16 25 32]
Multiplication: [ 20  80 150 320]
Division: [5. 5. 6. 5.]
Square: [ 100  400  900 1600]
Square Root: [3.16227766 4.47213595 5.47722558 6.32455532]

Vectorized 